export { default as FavoriteAlbumsPage } from '../pages/FavoriteAlbumsPage'
export { default as FavoriteArtistsPage } from '../pages/FavoriteArtistsPage'
export { default as FavoriteTracksPage } from '../pages/FavoriteTracksPage'
export { default as TopTracksPage } from '../pages/TopTracksPage'
export { default as SearchResultsPage } from '../pages/SearchResultsPage'
export { default as TopAlbumsPage } from '../pages/TopAlbumsPage'
export { default as TopArtistsPage } from '../pages/TopArtistsPage'
export { default as Home } from '../pages/Home'